name: build-and-push-docker
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.TOKEN_OWNER }}
          password: ${{ secrets.CR_PAT }}

      - name: Cache stack
        uses: actions/cache@v2
        env:
          cache-name: cache-stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Stack build
        run:  stack build

      - name: Copy over binary
        run: |
          cp "$(stack path --local-install-root)/bin/marvin-exe" .

      - name: Build Docker image
        run: docker build --push -t ghcr.io/mulan-szechuan-sauce/marvin:latest .

